### ISSUE TITLE
Monitor error - InvalidArgument, status code: 400

### ISSUE THREAD

**Issue by yanc0** [benbjohnson/litestream#74] opened 2021-02-22 16:59 UTC
Hi !

First of all, thank you for you great project. I am really exited to start new projects with SQLite.
I tried your last commits (**d6ece0b82644f8963fff1d20087bb07a6a2d99c4**) on master in order to upload generations into Google Cloud Storage.

Everything worked correctly until I tried to import a [~10MB CSV dataset into SQLite.](https://www.kaggle.com/kingburrito666/shakespeare-plays)

```bash
yann@xps:~/Projects/Perso/poc-litestream$ sqlite3 test.db
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> .mode csv
sqlite> .import ../Shakespeare_data.csv shakespear
_________________________________________
yann@xps:~/Projects/Perso/poc-litestream$ litestream replicate -config ~/Golang/bin/litestream.yml
litestream (development build)
initialized db: /home/yann/Projects/Perso/poc-litestream/test.db
replicating to: name="s3" type="s3" bucket="test-litestream-regional" path="db" region="europe-west1" endpoint="https://storage.googleapis.com" sync-interval=10s
/home/yann/Projects/Perso/poc-litestream/test.db(s3): monitor error: InvalidArgument: Invalid argument.
        status code: 400, request id: , host id:
/home/yann/Projects/Perso/poc-litestream/test.db(s3): monitor error: InvalidArgument: Invalid argument.
        status code: 400, request id: , host id:
_________________________________________
yann@xps:~/Projects/Perso/poc-litestream$ tree -ah
.
├── [9.3M]  test.db
├── [4.0K]  .test.db-litestream
│   ├── [  17]  generation
│   └── [4.0K]  generations
│       └── [4.0K]  310573930e9594aa
│           └── [4.0K]  wal
│               ├── [197K]  00000006.wal
│               ├── [9.4M]  00000007.wal
│               └── [4.1K]  00000008.wal
├── [ 32K]  test.db-shm
└── [9.4M]  test.db-wal

4 directories, 7 files

```

Here is my configuration:

```yaml
dbs:
 - path: /home/yann/Projects/Perso/poc-litestream/test.db
   replicas:
    - type: s3
      bucket: test-litestream-regional
      path: db
      endpoint: https://storage.googleapis.com
      forcePathStyle: true
      region: europe-west1
```

```bash
yann@xps:~/Projects/Perso/poc-litestream$ env | grep AWS
AWS_SECRET_ACCESS_KEY=<<REDACTED>>
AWS_ACCESS_KEY_ID=<<REDACTED>>
```

I wonder if this issue is GCP related of it is more general. I'm pretty sure the error is raised here: https://github.com/benbjohnson/litestream/blob/main/s3/s3.go#L818-L824

If I can do anything to help, I would love to !
Have a great day and Thank you !

**Comment by benbjohnson** [comment] 2021-02-22 17:18
Thanks for the bug report. I'll take a look locally and try to reproduce it. The `"InvalidArgument: Invalid argument`" error isn't a terribly helpful message. 😂

Trying the software and reporting bugs is the best way to help. Thanks so much!

**Comment by yanc0** [comment] 2021-02-24 07:56
If it can help, I tried to reproduce this bug using de [Scaleway's Object Storage](https://www.scaleway.com/en/object-storage/) and there is no problem. Big WAL's are successfully uploaded. I suspect a problem with the GCS interoperability mode.

**Comment by benbjohnson** [comment] 2021-02-24 17:56
Thanks for digging into that, @yanc0. I'll do some more testing with GCS to see if I can figure out what's going on.

**Comment by richard-lyman** [comment] 2021-04-15 01:20
I wonder which part of your config resulted in an invalid request...

https://github.com/benbjohnson/litestream.io/issues/22 links to https://github.com/richard-lyman/litestream.io/pull/1 which has a working CLI use of GCP that looks like this: `AWS_ACCESS_KEY_ID=<key> AWS_SECRET_ACCESS_KEY=<secret> litestream replicate /path/to/fruits.db s3://<bucket>.storage.googleapis.com/fruits.db`

Note how the bucket is a subdomain of `storage.googleapis.com`. I wonder how that working CLI invocation translates to a config file.

**Comment by richard-lyman** [comment] 2021-04-15 05:48
Left litestream running and now I'm seeing this error:

`fruits.db(s3): retain error: cannot delete generation "76d75af0c34fedfc" files before index
2: InvalidArgument: Invalid argument.
        status code: 400, request id: , host id:`

Some googling turned up a possibility: https://github.com/longhorn/longhorn/issues/1404#issuecomment-635699727 - with the follow-on question: does litestream use something like 'multi object delete functionality'?

From this line (https://github.com/benbjohnson/litestream/blob/main/s3/s3.go#L1109) it seems batch operations are used when deleting.

The section here (https://cloud.google.com/storage/docs/migrating#methods-comparison) outlining migration from S3 to Cloud Storage has several paragraphs outlining specific 'gotchas' as well as a table that has the note on lack of multi object delete.

Hope that helps.

**Comment by benbjohnson** [comment] 2021-04-16 22:04
Thanks for doing some more testing, @richard-lyman. I'm a little hesitant to refactor the batch delete since it'll affect other implementations and I'm going to refactor to use the GCP client soon anyway.

**Comment by richard-lyman** [comment] 2021-04-17 00:08
No worries. Thanks for all you're doing!

Feel free to ping me if I can help test anything.

**Comment by benbjohnson** [comment] 2021-04-25 15:31
I'm going to close this issue as I'm going to be working on native GCS support for Litestream v0.3.5 (#69).

**Closed by benbjohnson** 2021-04-25 15:31 UTC
Labels: bug
