### ISSUE TITLE
Litestream stack traces when it doesn't trust a TLS certificate

### ISSUE THREAD

**Issue by cablespaghetti** [benbjohnson/litestream#127] opened 2021-03-14 23:42 UTC
I have deployed MinIO in my Kubernetes cluster using [minio-operator](https://github.com/minio/operator), which doesn't seem to have a way to deploy without TLS. I haven't got as far as injecting the CA cert used into the litestream container so there is a certificate trust issue (see #126). I believe that's what's causing this stack trace.

This is with a Docker container built from the Dockerfile on the `docker` branch but code from the 0.3.3 tag. I wonder if that container is missing something required for certificate trust...although it works fine with AWS S3. I'll have a go with a less stripped down Debian based image using the "official" released binary if I get a moment.

Interestingly before I had the endpoint hostname set to the FQDN which is in the cert (I had it as just https://minio) I didn't get a stack trace, just a sensible error.

```
/db/db.db(s3): monitor error: RequestError: send request failed
caused by: Get "https://minio/mybkt?delimiter=%2F&prefix=db%2Fgenerations%2F": x509: certificate is valid for minio.default.svc.cluster.local, *.minio-hl.default.svc.cluster.local, *.default.svc.cluster.local, not minio
```

Here's my current config file (although I've tried a few different things):
```
addr: ":9090"
dbs:
  - path: /db/db.db
    replicas:
      - url: s3://mybkt/db.db
        endpoint: https://minio.default.svc.cluster.local
```

Here's the  log output:
```
litestream (development build)
initialized db: /db/db.db
replicating to: name="s3" type="s3" bucket="mybkt" path="db.db" region="" endpoint="https://minio.default.svc.cluster.local" sync-interval=10s
serving metrics on http://localhost:9090/metrics
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x47 pc=0x7f5a4edef1b9]

runtime stack:
runtime.throw(0xeb0e36, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 71 [syscall]:
runtime.cgocall(0xc4d190, 0xc0003a55c0, 0xc00018a058)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0003a5590 sp=0xc0003a5558 pc=0x40599b
net._C2func_getaddrinfo(0xc000025a40, 0x0, 0xc00018ca50, 0xc00018a058, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:94 +0x55 fp=0xc0003a55c0 sp=0xc0003a5590 pc=0x715675
net.cgoLookupIPCNAME.func1(0xc000025a40, 0x20, 0x20, 0xc00018ca50, 0xc00018a058, 0x0, 0xc0003a56a0, 0x718b92)
	/usr/local/go/src/net/cgo_unix.go:161 +0xc5 fp=0xc0003a5608 sp=0xc0003a55c0 pc=0x71b4e5
net.cgoLookupIPCNAME(0xe8e91e, 0x3, 0xc0004dec30, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:161 +0x16b fp=0xc0003a5718 sp=0xc0003a5608 pc=0x716b8b
net.cgoIPLookup(0xc000066c00, 0xe8e91e, 0x3, 0xc0004dec30, 0x1f)
	/usr/local/go/src/net/cgo_unix.go:218 +0x67 fp=0xc0003a57b8 sp=0xc0003a5718 pc=0x7172c7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0003a57c0 sp=0xc0003a57b8 pc=0x472221
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:228 +0xc7

goroutine 1 [chan receive]:
main.(*Main).Run(0xc00031ff58, 0xfd6e80, 0xc0000a2000, 0xc0000ae030, 0x0, 0x0, 0xc00008e058, 0x0)
	/go/src/github.com/benbjohnson/litestream/cmd/litestream/main.go:91 +0x670
main.main()
	/go/src/github.com/benbjohnson/litestream/cmd/litestream/main.go:38 +0xb0

goroutine 29 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:150 +0x45

goroutine 30 [chan receive]:
main.(*Main).Run.func1(0xc0000b7200, 0xc000099d60)
	/go/src/github.com/benbjohnson/litestream/cmd/litestream/main.go:84 +0x34
created by main.(*Main).Run
	/go/src/github.com/benbjohnson/litestream/cmd/litestream/main.go:84 +0x5f1

goroutine 31 [select]:
github.com/benbjohnson/litestream.(*DB).monitor(0xc000083380)
	/go/src/github.com/benbjohnson/litestream/db.go:1406 +0x11e
github.com/benbjohnson/litestream.(*DB).Open.func1(0xc000083380)
	/go/src/github.com/benbjohnson/litestream/db.go:285 +0x57
created by github.com/benbjohnson/litestream.(*DB).Open
	/go/src/github.com/benbjohnson/litestream/db.go:285 +0x2ae

goroutine 32 [IO wait]:
internal/poll.runtime_pollWait(0x7f5a659b0eb8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00012c618, 0x72, 0x0, 0x0, 0xe918eb)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00012c600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc00012c600, 0xc00015db00, 0x4103f8, 0xc00003ec00)
	/usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0000afd00, 0xc000048de0, 0x4103f8, 0x30)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0000afd00, 0xe32400, 0xc00015db00, 0xda2b80, 0x143b0c0)
	/usr/local/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc00017c000, 0xfd3500, 0xc0000afd00, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2937 +0x266
net/http.(*Server).ListenAndServe(0xc00017c000, 0xc00017c000, 0x8)
	/usr/local/go/src/net/http/server.go:2866 +0xb7
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3120
main.(*ReplicateCommand).Run.func1(0xc0000b7020)
	/go/src/github.com/benbjohnson/litestream/cmd/litestream/replicate.go:128 +0xbe
created by main.(*ReplicateCommand).Run
	/go/src/github.com/benbjohnson/litestream/cmd/litestream/replicate.go:126 +0x98b

goroutine 52 [select]:
database/sql.(*DB).connectionOpener(0xc00013d790, 0xfd6e40, 0xc0000d32c0)
	/usr/local/go/src/database/sql/sql.go:1126 +0xf5
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:740 +0x12a

goroutine 54 [chan receive]:
database/sql.(*Tx).awaitDone(0xc00012c700)
	/usr/local/go/src/database/sql/sql.go:2063 +0x4b
created by database/sql.(*DB).beginDC
	/usr/local/go/src/database/sql/sql.go:1779 +0x1e5

goroutine 56 [select]:
net/http.(*Transport).getConn(0x1446dc0, 0xc0005a0c00, 0x0, 0xc0000a04e0, 0x5, 0xc0004dec30, 0x23, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1350 +0x5ac
net/http.(*Transport).roundTrip(0x1446dc0, 0xc00032a100, 0x30, 0x7f5a8de48958, 0x150)
	/usr/local/go/src/net/http/transport.go:569 +0x7ce
net/http.(*Transport).RoundTrip(0x1446dc0, 0xc00032a100, 0x1446dc0, 0x0, 0x0)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc00032a100, 0xfc75e0, 0x1446dc0, 0x0, 0x0, 0x0, 0xc00018a040, 0xc0003cd528, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:252 +0x453
net/http.(*Client).send(0x1493380, 0xc00032a100, 0x0, 0x0, 0x0, 0xc00018a040, 0x0, 0x1, 0x5)
	/usr/local/go/src/net/http/client.go:176 +0xff
net/http.(*Client).do(0x1493380, 0xc00032a100, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:586
github.com/aws/aws-sdk-go/aws/corehandlers.sendFollowRedirects(0xc000150f00, 0xc00032a100, 0xc0001688c0, 0x0)
	/go/pkg/mod/github.com/aws/aws-sdk-go@v1.27.0/aws/corehandlers/handlers.go:120 +0x3b
github.com/aws/aws-sdk-go/aws/corehandlers.glob..func3(0xc000150f00)
	/go/pkg/mod/github.com/aws/aws-sdk-go@v1.27.0/aws/corehandlers/handlers.go:112 +0x9d
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc000151100, 0xc000150f00)
	/go/pkg/mod/github.com/aws/aws-sdk-go@v1.27.0/aws/request/handlers.go:267 +0x9a
github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc000150f00, 0x0, 0x0)
	/go/pkg/mod/github.com/aws/aws-sdk-go@v1.27.0/aws/request/request.go:578 +0xae
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc000150f00, 0x0, 0x0)
	/go/pkg/mod/github.com/aws/aws-sdk-go@v1.27.0/aws/request/request.go:531 +0x107
github.com/aws/aws-sdk-go/aws/request.(*Pagination).Next(0xc0003cd9f8, 0xc0000d3a80)
	/go/pkg/mod/github.com/aws/aws-sdk-go@v1.27.0/aws/request/request_pagination.go:107 +0x145
github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsPagesWithContext(0xc0000b4540, 0xfd6e80, 0xc0000a2000, 0xc0000d3a40, 0xc0003cdae8, 0x0, 0x0, 0x0, 0x7f5a659aa7e0, 0x0)
	/go/pkg/mod/github.com/aws/aws-sdk-go@v1.27.0/service/s3/api.go:5952 +0x107
github.com/benbjohnson/litestream/s3.(*Replica).Generations(0xc00016c000, 0xfd6e80, 0xc0000a2000, 0x0, 0x0, 0xc000083c80, 0xc0003cdb90, 0x46d285)
	/go/src/github.com/benbjohnson/litestream/s3/s3.go:209 +0x29e
github.com/benbjohnson/litestream/s3.(*Replica).Snapshots(0xc00016c000, 0xfd6e80, 0xc0000a2000, 0x4ec4fd, 0xc0003bb040, 0xc00014ee10, 0x43, 0xc0003bb078)
	/go/src/github.com/benbjohnson/litestream/s3/s3.go:325 +0x98
github.com/benbjohnson/litestream/s3.(*Replica).snapshotN(0xc00016c000, 0xc0000c3c20, 0x10, 0x0, 0x0, 0x0)
	/go/src/github.com/benbjohnson/litestream/s3/s3.go:708 +0x47
github.com/benbjohnson/litestream/s3.(*Replica).Sync.func2(0xc00016c000, 0xc0000c3c20, 0x10, 0xfd6e40, 0xc0000d3700, 0xc0000c3c20, 0x10, 0x2, 0x1038, 0x0, ...)
	/go/src/github.com/benbjohnson/litestream/s3/s3.go:829 +0xb4
github.com/benbjohnson/litestream/s3.(*Replica).Sync(0xc00016c000, 0xfd6e40, 0xc0000d3700, 0x0, 0x0)
	/go/src/github.com/benbjohnson/litestream/s3/s3.go:851 +0x3b0
github.com/benbjohnson/litestream/s3.(*Replica).monitor(0xc00016c000, 0xfd6e40, 0xc0000d3700)
	/go/src/github.com/benbjohnson/litestream/s3/s3.go:497 +0x1d3
github.com/benbjohnson/litestream/s3.(*Replica).Start.func1(0xc00016c000, 0xfd6e40, 0xc0000d3700)
	/go/src/github.com/benbjohnson/litestream/s3/s3.go:437 +0x6c
created by github.com/benbjohnson/litestream/s3.(*Replica).Start
	/go/src/github.com/benbjohnson/litestream/s3/s3.go:437 +0xde

goroutine 57 [select]:
github.com/benbjohnson/litestream/s3.(*Replica).retainer(0xc00016c000, 0xfd6e40, 0xc0000d3700)
	/go/src/github.com/benbjohnson/litestream/s3/s3.go:521 +0x145
github.com/benbjohnson/litestream/s3.(*Replica).Start.func2(0xc00016c000, 0xfd6e40, 0xc0000d3700)
	/go/src/github.com/benbjohnson/litestream/s3/s3.go:438 +0x6c
created by github.com/benbjohnson/litestream/s3.(*Replica).Start
	/go/src/github.com/benbjohnson/litestream/s3/s3.go:438 +0x114

goroutine 69 [select]:
net.(*Resolver).lookupIPAddr(0x1492ac0, 0xfd6ec0, 0xc000066b40, 0xe8e91e, 0x3, 0xc0004dec30, 0x1f, 0x1bb, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup.go:299 +0x685
net.(*Resolver).internetAddrList(0x1492ac0, 0xfd6ec0, 0xc000066b40, 0xe8e91e, 0x3, 0xc0004dec30, 0x23, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:280 +0x4d4
net.(*Resolver).resolveAddrList(0x1492ac0, 0xfd6ec0, 0xc000066b40, 0xe8eec3, 0x4, 0xe8e91e, 0x3, 0xc0004dec30, 0x23, 0x0, ...)
	/usr/local/go/src/net/dial.go:221 +0x47d
net.(*Dialer).DialContext(0xc0000b64e0, 0xfd6e80, 0xc0000a2000, 0xe8e91e, 0x3, 0xc0004dec30, 0x23, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:403 +0x22b
net/http.(*Transport).dial(0x1446dc0, 0xfd6e80, 0xc0000a2000, 0xe8e91e, 0x3, 0xc0004dec30, 0x23, 0x0, 0xc0000b45b0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1144 +0x1fd
net/http.(*Transport).dialConn(0x1446dc0, 0xfd6e80, 0xc0000a2000, 0x0, 0xc0000a04e0, 0x5, 0xc0004dec30, 0x23, 0x0, 0xc000216120, ...)
	/usr/local/go/src/net/http/transport.go:1578 +0x1abb
net/http.(*Transport).dialConnFor(0x1446dc0, 0xc0000d1550)
	/usr/local/go/src/net/http/transport.go:1424 +0xc6
created by net/http.(*Transport).queueForDial
	/usr/local/go/src/net/http/transport.go:1393 +0x40f

goroutine 70 [select]:
net.cgoLookupIP(0xfd6e40, 0xc0005a0c40, 0xe8e91e, 0x3, 0xc0004dec30, 0x1f, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:229 +0x199
net.(*Resolver).lookupIP(0x1492ac0, 0xfd6e40, 0xc0005a0c40, 0xe8e91e, 0x3, 0xc0004dec30, 0x1f, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup_unix.go:96 +0x187
net.glob..func1(0xfd6e40, 0xc0005a0c40, 0xc000051df0, 0xe8e91e, 0x3, 0xc0004dec30, 0x1f, 0xc0000a2000, 0x0, 0xc0000a04e0, ...)
	/usr/local/go/src/net/hook.go:23 +0x72
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:293 +0xb9
internal/singleflight.(*Group).doCall(0x1492ad0, 0xc0000714f0, 0xc0004dec60, 0x23, 0xc0005a0c80)
	/usr/local/go/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2cc
```

**Comment by benbjohnson** [comment] 2021-03-27 14:07
Sorry it's taken so long for me to get back to you, Sam. I'd be curious if #141 fixes this for you. Obviously, a panic isn't the right thing to do but the stack trace doesn't give a lot of information:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x47 pc=0x7f5a4edef1b9]

runtime stack:
runtime.throw(0xeb0e36, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac
```

It seems like it's something going on outside the application layer so I wonder if switching to a less stripped down Docker image would help. Also, I pushed up some static builds on the `v0.3.4-alpha4` release that might help.

**Comment by benbjohnson** [comment] 2021-04-17 15:23
@cablespaghetti I think the issue might be that the static builds of Litestream were compiling against the cgo version of the `net` package. I pushed up a change and built a new alpha release (`v0.3.4-alpha21`) which compiles in a Go version of `net`. If possible, would you be able to try against that version?

**Comment by benbjohnson** [comment] 2021-04-21 18:19
I'm going to close this out as I can't reproduce it and I _think_ compiling with `netgo` should fix this. Please let me know if anyone hits this issue again.

**Closed by benbjohnson** 2021-04-21 18:19 UTC
Labels: bug
