### ISSUE TITLE
cannot verify wal state: ...-wal: no such file or directory

### ISSUE THREAD

**Issue by simon-weber** [benbjohnson/litestream#79] opened 2021-02-24 04:04 UTC
I'm testing out a litestream setup on k8s, where a python app container and litestream container share the db via a local volume. The db is created via an init container that just runs `CREATE TABLE` before either of them start.

Here is what init looks like:
```
litestream v0.3.2
initialized db: /db/hello.sqlite3
replicating to: name="s3" type="s3" bucket="..." path="hello.sqlite3" region=""
litestream /db/hello.sqlite3: init: cannot determine last wal position, clearing generation (primary wal header: EOF)
litestream /db/hello.sqlite3: sync: new generation "b7852795bc0c7d42", no generation exists
```

Afterwards, I get no logs until I run a query through the app (read or write). Then, I get a steady stream of `litestream /db/hello.sqlite3: sync error: cannot verify wal state: stat /db/hello.sqlite3-wal: no such file or directory` until I shut down litestream. I've tried issuing the wal pragma from the app's connection and enabling autocommit mode, but neither seem to make a difference.

Similar to https://github.com/benbjohnson/litestream/issues/58, I'm wondering if I'm doing something wrong or whether this is a litestream bug. If you think it's the latter, I can try to work on a simpler repro (I haven't tried it locally yet).

**Comment by maluio** [comment] 2021-02-24 12:14
I get the same error in my local setup (no docker/k8s at this point) when I start my Django app BEFORE I start the `litestream replicate` command.

My guess would be that your K8s setup doesn't guarantee that the litestream container runs before the app. The init container is only responsible for creating the DB, but this is not sufficient.

In fact, I've been starting to think about a K8s setup, but due to this very issue I might rather run litestream as a stateful set and share the DB files for my smallish Django apps via a persistent volume claim.

**Comment by angelbarrera92** [comment] 2021-02-24 12:22
I had that issue yesterday. It was solved ensuring litestream can read the database. Try running it with `sudo`.

**Comment by maluio** [comment] 2021-02-24 12:27
In my case, this was not issue with permissions. I could resolve the problem by stopping both litestream and my Django app, and starting litestream BEFORE starting my Django app.

**Comment by benbjohnson** [comment] 2021-02-24 14:49
Thanks for reporting the bug. I think this should be fixed with #59 which I'm going to work on today. Litestream requires a WAL to be present so it forces one but if that fails then it puts Litestream in a state where it won't try to reinitialize until you restart the process.

**Comment by benbjohnson** [comment] 2021-02-24 22:49
This initialization issue should be fixed now: https://github.com/benbjohnson/litestream/pull/82

Let me know if you all still have any issues with it.

**Comment by simon-weber** [comment] 2021-02-26 00:47
Unfortunately, no change for me using a source build of f652186adf7470256b6a7bf7e96194dde49c2af2. Starting litestream first doesn't seem to make a difference either.

This works to repro for me locally:
```
$ ./litestream replicate repro.sqlite3 s3://[...]/repro.sqlite3 &
litestream (development build)
initialized db: [...]repro.sqlite3
replicating to: name="s3" type="s3" bucket="[...]" path="repro.sqlite3" region="" endpoint="" sync-interval=1s

$ python -c 'import sqlite3; conn = sqlite3.connect("repro.sqlite3"); c = conn.cursor(); c.execute("CREATE TABLE IF NOT EXISTS t ( id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL )"); conn.commit(); conn.close();'
repro.sqlite3(s3): snapshot: creating 53fd9b6138e3b530/00000000 t=72ms

$ python -c 'import sqlite3; conn = sqlite3.connect("repro.sqlite3"); c = conn.cursor(); c.execute("INSERT INTO t DEFAULT VALUES"); conn.commit(); conn.close();'
repro.sqlite3: sync error: cannot verify wal state: stat [...]repro.sqlite3-wal: no such file or directory
repro.sqlite3: sync error: cannot verify wal state: stat [...]repro.sqlite3-wal: no such file or directory
```

It doesn't seem to make a difference if I add `c.execute("pragma journal_mode=wal")` before the other queries.

**Comment by benbjohnson** [comment] 2021-02-26 01:05
Thanks for testing out the change. I’ll reopen and take another look.

**Comment by benbjohnson** [comment] 2021-02-27 16:50
@simon-weber I was able to reproduce the issue and I have a fix (https://github.com/benbjohnson/litestream/pull/93) but I'm going to do more testing before I merge it. The issue was that closing any database file descriptor releases all locks on the descriptor on operating systems that don't support OFD locks. There's a long-running transaction that is meant to prevent checkpoints by outside SQLite instances but this lock release prevents that from working.

Thanks again for posting the issue and testing it out!

**Closed** 2021-02-28 14:28 UTC
Labels: bug

**Comment by benbjohnson** [comment] 2021-02-28 14:29
I did some more testing on #93 and ran it over night. It's merged (which closed this issue) but I'll re-open this issue if anyone's still experiencing issues.

**Comment by cablespaghetti** [comment] 2021-03-06 22:52
Was having this issue with 0.3.2, but not with the latest commit. :+1:
