### ISSUE TITLE
cannot find snapshot index by timestamp: no snapshots available

### ISSUE THREAD

**Issue by mtlynch** [benbjohnson/litestream#251] opened 2021-12-04 10:53 UTC
When I try to restore from a backup, I get the following error:

```bash
$ litestream restore -config litestream.yml -o data/prod-2021-12-04.db -v data/store.db
cannot find snapshot index by timestamp: no snapshots available
```

If I run `litestream snapshots`, I can see a snapshot, but it's four days old. I've run `litestream snapshots` a few times in the past few days, and there was at one point a snapshot from 2021-12-01 that has since disappeared.

```bash
$ litestream snapshots -config litestream.yml data/store.db
replica  generation        index  size     created
s3       5dfeb4aa03232553  24     1389251  2021-11-30T04:38:34Z

$ litestream generations -config litestream.yml data/store.db
name  generation        lag         start                 end
s3    29cf4bced74e92ab  -104h48m2s  2021-12-04T09:32:10Z  2021-12-04T10:23:29Z
s3    5dfeb4aa03232553  -22h11m26s  2021-11-30T03:40:32Z  2021-11-30T23:46:53Z
```

I see this error in my logs. It doesn't look like Litestream has been logging for the past day:

```
/app/data/store.db(s3): retainer error: snapshots: cannot fetch generations: InternalError: Internal Error
```

Building 755f54f4d9b51885076f7aa31334389056361ea7 from source allowed me to retrieve the backup, but it's a few days out of date. I'm guessing it's the snapshot from 2021-11-30:

```bash
$ ./dist/litestream restore -config ../whatgotdone/litestream.yml -o ../tmp/prod-2021-12-04.db -v data/store.db
2021/12/04 05:41:11.231140 /home/mike/whatgotdone/data/store.db(s3): restoring snapshot 5dfeb4aa03232553/00000018 to ../tmp/prod-2021-12-04.db.tmp
2021/12/04 05:41:13.165836 /home/mike/whatgotdone/data/store.db(s3): snapshot only, finalizing database

$ git rev-parse HEAD
755f54f4d9b51885076f7aa31334389056361ea7
```

On Backblaze, I see the same two generations that `litestream generations` reports:

![image](https://user-images.githubusercontent.com/7783288/144706802-3664cdbe-af42-488d-a0dc-118066eb32e7.png)

I've saved a snapshot of them, and I can share the data privately with you if you'd like.

### Version

```bash
$ litestream version
v0.3.6
```

### Config

```yaml
access-key-id: ${LITESTREAM_ACCESS_KEY_ID}
secret-access-key: ${LITESTREAM_SECRET_ACCESS_KEY}
dbs:
  - path: ${DB_PATH}
    replicas:
      - type: s3
        bucket: ${LITESTREAM_BUCKET}
        path: db
        endpoint: ${LITESTREAM_ENDPOINT}
        force-path-style: true
        retention: 720h # 30 days
```

https://github.com/mtlynch/whatgotdone/blob/2cc4d9811fe7cb271c1187c3b3ff35de0beca087/litestream.yml

### Logs

https://gist.github.com/mtlynch/38b3eafa88f097de78141f103e7bdc0e

In the logs, `b5a3` and `262d` are different deployments of my app.

**Comment by benbjohnson** [comment] 2021-12-04 17:42
hey Michael, thanks for reporting the bug. That seems odd that it's not picking up the snapshot. I don't see the issue from an initial look at the code so I think the data will be helpful. I'll send you an upload link via Twitter DM.

**Comment by mtlynch** [comment] 2021-12-04 17:51
> I'll send you an upload link via Twitter DM.

Thanks, I've uploaded it.

Will setting `validation-interval` in my litestream.yml reduce the likelihood of data loss here? I was able to recover the data by SSHing into the machine and manually scp'ing the data out, but I think I would have lost a few days of data had I just gone through my normal workflow of tearing down the live instance and deploying a new one to pull down the latest litestream snapshot.

**Comment by benbjohnson** [comment] 2021-12-04 18:22
Ok, it looks like the issue with `"no snapshots available"` error is that `29cf4bced74e92ab` has WAL files but no snapshot. The `restore` command automatically tries to find the latest generation when no `-generation` is specified and it picked `29cf4bced74e92ab` since it has the most recent WAL files.

As for the missing snapshot, I'm still looking into that. It looks like the snapshot is created and then immediately deleted:

```
2021-12-01T03:27:13.766Z,262d,,"/app/data/store.db: sync: new generation ""29cf4bced74e92ab"", no generation exists"
2021-12-01T03:27:19.879Z,262d,,/app/data/store.db(s3): snapshot written 29cf4bced74e92ab/00000000
2021-12-01T04:27:19.177Z,262d,,/app/data/store.db(s3): snapshot deleted 29cf4bced74e92ab/00000018
2021-12-01T04:27:19.177Z,262d,,/app/data/store.db(s3): wal segmented deleted before 29cf4bced74e92ab/00000018: n=3
2021-12-02T22:27:23.620Z,262d,,/app/data/store.db(s3): retainer error: snapshots: cannot fetch generations: InternalError: Internal Error
```

The retention enforcement seems to think that index 18 is the lowest snapshot written for that generation but it's not—it should be zero. It looks like it might be getting the `18` from the other generation (`5dfeb4aa03232553`) but I'm honestly not sure how it's doing that.

This is just my initial investigation on it. I'll see if I can get something reproduced and fixed.

**Comment by benbjohnson** [comment] 2021-12-05 16:44
@mtlynch I found the issue and it was dumb. It's fixed in https://github.com/benbjohnson/litestream/pull/252. I'm surprised the issue hasn't come up earlier although I suspect you would be more likely to see it because you don't use a persistent disk so you end up with more frequent generations. I'm going to cut a new release and it'll be ready shortly. Thanks again for reporting the issue!

**Comment by benbjohnson** [comment] 2021-12-05 17:19
@mtlynch I released a new version of Litestream with the fix: https://github.com/benbjohnson/litestream/releases/tag/v0.3.7

**Closed by benbjohnson** 2021-12-05 17:19 UTC
Labels: bug

**Comment by mtlynch** [comment] 2021-12-05 19:25
@benbjohnson - Awesome, thanks for the fix! Glad you were able to repro and produce a test case for it.
