### ISSUE TITLE
WAL not seen on Backblaze B2

### ISSUE THREAD

**Issue by kurtis-poole** [benbjohnson/litestream#264] opened 2022-01-11 16:14 UTC
### Discussed in https://github.com/benbjohnson/litestream/discussions/263

Issue from discussion: litestream restore / generations / snapshots / wal does not seem to pick up WAL files on B2

Replicate works and syncs WAL upstream, with files present in the B2 bucket

?peculiarity retrieving from B2's API

**Comment by benbjohnson** [comment] 2022-01-11 20:55
Thanks for converting this to an issue. I tagged this for fix for `v0.4.0`. 👍

**Comment by benbjohnson** [comment] 2022-03-06 15:16
@kurtis-poole I did some testing on this bug today and I'm not able to reproduce it anymore. A lot of the replica code has been refactored and cleaned up for the `v0.4.0` release so it may have been fixed as part of that. I'm going to close this now but we can re-open it if there continues to be an issue.

**Closed by benbjohnson** 2022-03-06 15:16 UTC
Labels: bug
